version: '3.8'
services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=business_ai
    ports:
      - "5435:5432"

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
      
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - EMAIL=admin@infinitylabscol.com
      - DOMAIN=noit.com.co
      - DOMAIN_WWW=www.noit.com.co
    entrypoint: "/bin/sh -c '\
      if [ ! -d /etc/letsencrypt/live/$$DOMAIN ]; then \
        certbot certonly --webroot --webroot-path=/var/www/certbot \
          --email $$EMAIL --agree-tos --no-eff-email \
          -d $$DOMAIN -d $$DOMAIN_WWW || exit 1; \
      fi; \
      trap exit TERM; \
      while :; do \
        certbot renew; \
        sleep 12h & wait $${!}; \
      done;'"

volumes:
  postgres_data:
  redis_data:
  certbot_data: