"""research task

Revision ID: 05f36c88e0b5
Revises: 8501cab94b4a
Create Date: 2025-04-13 12:29:33.824164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f36c88e0b5'
down_revision: Union[str, None] = '8501cab94b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_understanding_id', sa.String(), nullable=True),
    sa.Column('business_idea_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('research_type', sa.String(), nullable=False),
    sa.Column('depth', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.String(), nullable=False),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_understanding_id'], ['business_understanding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_tasks_id'), 'research_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_research_tasks_request_id'), 'research_tasks', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_tasks_request_id'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_id'), table_name='research_tasks')
    op.drop_table('research_tasks')
    # ### end Alembic commands ###
