"""add brief service compatibility with chat orchestrator

Revision ID: 0b3eea949ded
Revises: 0f764e78cf4b
Create Date: 2025-04-11 23:29:20.594416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3eea949ded'
down_revision: Union[str, None] = '0f764e78cf4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
