"""add relationships between BusinessIdea and BusinessProgress

Revision ID: 0f764e78cf4b
Revises: 6baecb22dfd8
Create Date: 2025-04-11 23:22:55.269948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f764e78cf4b'
down_revision: Union[str, None] = '6baecb22dfd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
