"""initial migration

Revision ID: 31aa1e743370
Revises: 
Create Date: 2025-02-18 21:29:10.772192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31aa1e743370'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_user_info',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('follows_count', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('business_category', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=2083), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('total_posts', sa.Integer(), nullable=False),
    sa.Column('igtv_videos', sa.Integer(), nullable=True),
    sa.Column('highlight_reels', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_instagram_user_info_id'), 'instagram_user_info', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('business_ideas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_ideas_id'), 'business_ideas', ['id'], unique=False)
    op.create_table('instagram_posts_info',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instagram_user_id', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mentions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('is_sponsored', sa.Boolean(), nullable=True),
    sa.Column('post_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instagram_user_id'], ['instagram_user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_posts_info_id'), 'instagram_posts_info', ['id'], unique=False)
    op.create_table('instagram_user_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('final_insight', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_user_insights_id'), 'instagram_user_insights', ['id'], unique=False)
    op.create_table('business_canvas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_idea_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('bucket_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_idea_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_canvas_id'), 'business_canvas', ['id'], unique=False)
    op.create_table('business_validations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'ERROR', name='validationstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('report_url', sa.String(), nullable=True),
    sa.Column('data_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_validations_id'), 'business_validations', ['id'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_idea_id', sa.String(), nullable=True),
    sa.Column('competitor_name', sa.String(), nullable=False),
    sa.Column('key_feature', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('x_url', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_idea_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_id'), 'competitors', ['id'], unique=False)
    op.create_table('instagram_post_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('llm_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_index(op.f('ix_instagram_post_images_id'), 'instagram_post_images', ['id'], unique=False)
    op.create_table('instagram_image_colors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('red', sa.Integer(), nullable=False),
    sa.Column('green', sa.Integer(), nullable=False),
    sa.Column('blue', sa.Integer(), nullable=False),
    sa.Column('proportion', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('blue >= 0 AND blue <= 255', name='valid_blue'),
    sa.CheckConstraint('green >= 0 AND green <= 255', name='valid_green'),
    sa.CheckConstraint('proportion >= 0 AND proportion <= 1', name='valid_proportion'),
    sa.CheckConstraint('red >= 0 AND red <= 255', name='valid_red'),
    sa.ForeignKeyConstraint(['image_id'], ['instagram_post_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_image_colors_id'), 'instagram_image_colors', ['id'], unique=False)
    op.create_table('instagram_scraping_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('competitor_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('dataset_id_post', sa.String(), nullable=True),
    sa.Column('dataset_id_image', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_scraping_jobs_id'), 'instagram_scraping_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_scraping_jobs_id'), table_name='instagram_scraping_jobs')
    op.drop_table('instagram_scraping_jobs')
    op.drop_index(op.f('ix_instagram_image_colors_id'), table_name='instagram_image_colors')
    op.drop_table('instagram_image_colors')
    op.drop_index(op.f('ix_instagram_post_images_id'), table_name='instagram_post_images')
    op.drop_table('instagram_post_images')
    op.drop_index(op.f('ix_competitors_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_business_validations_id'), table_name='business_validations')
    op.drop_table('business_validations')
    op.drop_index(op.f('ix_business_canvas_id'), table_name='business_canvas')
    op.drop_table('business_canvas')
    op.drop_index(op.f('ix_instagram_user_insights_id'), table_name='instagram_user_insights')
    op.drop_table('instagram_user_insights')
    op.drop_index(op.f('ix_instagram_posts_info_id'), table_name='instagram_posts_info')
    op.drop_table('instagram_posts_info')
    op.drop_index(op.f('ix_business_ideas_id'), table_name='business_ideas')
    op.drop_table('business_ideas')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_instagram_user_info_id'), table_name='instagram_user_info')
    op.drop_table('instagram_user_info')
    # ### end Alembic commands ###
