"""initial tables

Revision ID: 642cbc19a411
Revises: 
Create Date: 2025-03-02 21:59:57.875825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '642cbc19a411'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_user_info',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('follows_count', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('business_category', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=2083), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('total_posts', sa.Integer(), nullable=False),
    sa.Column('igtv_videos', sa.Integer(), nullable=True),
    sa.Column('highlight_reels', sa.Integer(), nullable=True),
    sa.Column('address_city_name', sa.String(length=255), nullable=True),
    sa.Column('address_lat', sa.Float(), nullable=True),
    sa.Column('address_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_instagram_user_info_id'), 'instagram_user_info', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('business_ideas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_ideas_id'), 'business_ideas', ['id'], unique=False)
    op.create_table('instagram_comment_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category_type', sa.String(length=100), nullable=False),
    sa.Column('category_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_comment_categories_id'), 'instagram_comment_categories', ['id'], unique=False)
    op.create_table('instagram_lda_topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('topic_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_lda_topics_id'), 'instagram_lda_topics', ['id'], unique=False)
    op.create_table('instagram_posts_info',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_post', sa.String(), nullable=False),
    sa.Column('instagram_user_id', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mentions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('is_sponsored', sa.Boolean(), nullable=True),
    sa.Column('post_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type_post', sa.String(length=50), nullable=True),
    sa.Column('url_post', sa.String(length=2083), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instagram_user_id'], ['instagram_user_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_post')
    )
    op.create_index(op.f('ix_instagram_posts_info_id'), 'instagram_posts_info', ['id'], unique=False)
    op.create_table('instagram_user_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('final_insight', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_user_insights_id'), 'instagram_user_insights', ['id'], unique=False)
    op.create_table('instagram_user_sentiment_overview',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('positive_comments', sa.Integer(), nullable=False),
    sa.Column('negative_comments', sa.Integer(), nullable=False),
    sa.Column('neutral_comments', sa.Integer(), nullable=False),
    sa.Column('positive_ratio', sa.Float(), nullable=False),
    sa.Column('negative_ratio', sa.Float(), nullable=False),
    sa.Column('neutral_ratio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_user_sentiment_overview_id'), 'instagram_user_sentiment_overview', ['id'], unique=False)
    op.create_table('multi_account_comment_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category_type', sa.String(length=100), nullable=False),
    sa.Column('category_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_account_comment_categories_id'), 'multi_account_comment_categories', ['id'], unique=False)
    op.create_table('multi_account_lda_topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('topic_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_account_lda_topics_id'), 'multi_account_lda_topics', ['id'], unique=False)
    op.create_table('multi_account_sentiment_overview',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('positive_comments', sa.Integer(), nullable=False),
    sa.Column('negative_comments', sa.Integer(), nullable=False),
    sa.Column('neutral_comments', sa.Integer(), nullable=False),
    sa.Column('positive_ratio', sa.Float(), nullable=False),
    sa.Column('negative_ratio', sa.Float(), nullable=False),
    sa.Column('neutral_ratio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_account_sentiment_overview_id'), 'multi_account_sentiment_overview', ['id'], unique=False)
    op.create_table('business_canvas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_idea_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('bucket_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_idea_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_canvas_id'), 'business_canvas', ['id'], unique=False)
    op.create_table('business_understanding',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_idea_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_research_path', sa.String(), nullable=True),
    sa.Column('state_of_art_path', sa.String(), nullable=True),
    sa.Column('market_research_status', sa.String(), nullable=True),
    sa.Column('state_of_art_status', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_idea_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_understanding_id'), 'business_understanding', ['id'], unique=False)
    op.create_table('business_validations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'ERROR', name='validationstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('data_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_validations_id'), 'business_validations', ['id'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_idea_id', sa.String(), nullable=True),
    sa.Column('competitor_name', sa.String(), nullable=False),
    sa.Column('key_feature', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('x_url', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('tiktok_url', sa.String(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_idea_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_id'), 'competitors', ['id'], unique=False)
    op.create_table('instagram_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('username_commentator', sa.String(length=50), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_comments_id'), 'instagram_comments', ['id'], unique=False)
    op.create_table('instagram_post_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('llm_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_index(op.f('ix_instagram_post_images_id'), 'instagram_post_images', ['id'], unique=False)
    op.create_table('instagram_post_sentiment_summary',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('positive_comments', sa.Integer(), nullable=False),
    sa.Column('negative_comments', sa.Integer(), nullable=False),
    sa.Column('neutral_comments', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_post_sentiment_summary_id'), 'instagram_post_sentiment_summary', ['id'], unique=False)
    op.create_table('multi_account_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['multi_account_comment_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_account_comments_id'), 'multi_account_comments', ['id'], unique=False)
    op.create_table('instagram_comment_emotions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('emotion_label', sa.String(length=50), nullable=False),
    sa.Column('emotion_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['instagram_comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_comment_emotions_id'), 'instagram_comment_emotions', ['id'], unique=False)
    op.create_table('instagram_comment_sentiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('sentiment_negative', sa.Float(), nullable=False),
    sa.Column('sentiment_neutral', sa.Float(), nullable=False),
    sa.Column('sentiment_positive', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['instagram_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_comment_sentiments_id'), 'instagram_comment_sentiments', ['id'], unique=False)
    op.create_table('instagram_image_colors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('red', sa.Integer(), nullable=False),
    sa.Column('green', sa.Integer(), nullable=False),
    sa.Column('blue', sa.Integer(), nullable=False),
    sa.Column('proportion', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('blue >= 0 AND blue <= 255', name='valid_blue'),
    sa.CheckConstraint('green >= 0 AND green <= 255', name='valid_green'),
    sa.CheckConstraint('proportion >= 0 AND proportion <= 1', name='valid_proportion'),
    sa.CheckConstraint('red >= 0 AND red <= 255', name='valid_red'),
    sa.ForeignKeyConstraint(['image_id'], ['instagram_post_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_image_colors_id'), 'instagram_image_colors', ['id'], unique=False)
    op.create_table('instagram_scraping_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('competitor_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('dataset_id_profile', sa.String(), nullable=True),
    sa.Column('dataset_id_posts', sa.String(), nullable=True),
    sa.Column('dataset_id_comments', sa.String(), nullable=True),
    sa.Column('dataset_id_reels', sa.String(), nullable=True),
    sa.Column('dataset_id_igtv', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('profile_status', sa.String(), nullable=True),
    sa.Column('posts_status', sa.String(), nullable=True),
    sa.Column('comments_status', sa.String(), nullable=True),
    sa.Column('reels_status', sa.String(), nullable=True),
    sa.Column('igtv_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results_limit', sa.Integer(), nullable=True),
    sa.Column('max_comments', sa.Integer(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_scraping_jobs_id'), 'instagram_scraping_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_scraping_jobs_id'), table_name='instagram_scraping_jobs')
    op.drop_table('instagram_scraping_jobs')
    op.drop_index(op.f('ix_instagram_image_colors_id'), table_name='instagram_image_colors')
    op.drop_table('instagram_image_colors')
    op.drop_index(op.f('ix_instagram_comment_sentiments_id'), table_name='instagram_comment_sentiments')
    op.drop_table('instagram_comment_sentiments')
    op.drop_index(op.f('ix_instagram_comment_emotions_id'), table_name='instagram_comment_emotions')
    op.drop_table('instagram_comment_emotions')
    op.drop_index(op.f('ix_multi_account_comments_id'), table_name='multi_account_comments')
    op.drop_table('multi_account_comments')
    op.drop_index(op.f('ix_instagram_post_sentiment_summary_id'), table_name='instagram_post_sentiment_summary')
    op.drop_table('instagram_post_sentiment_summary')
    op.drop_index(op.f('ix_instagram_post_images_id'), table_name='instagram_post_images')
    op.drop_table('instagram_post_images')
    op.drop_index(op.f('ix_instagram_comments_id'), table_name='instagram_comments')
    op.drop_table('instagram_comments')
    op.drop_index(op.f('ix_competitors_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_business_validations_id'), table_name='business_validations')
    op.drop_table('business_validations')
    op.drop_index(op.f('ix_business_understanding_id'), table_name='business_understanding')
    op.drop_table('business_understanding')
    op.drop_index(op.f('ix_business_canvas_id'), table_name='business_canvas')
    op.drop_table('business_canvas')
    op.drop_index(op.f('ix_multi_account_sentiment_overview_id'), table_name='multi_account_sentiment_overview')
    op.drop_table('multi_account_sentiment_overview')
    op.drop_index(op.f('ix_multi_account_lda_topics_id'), table_name='multi_account_lda_topics')
    op.drop_table('multi_account_lda_topics')
    op.drop_index(op.f('ix_multi_account_comment_categories_id'), table_name='multi_account_comment_categories')
    op.drop_table('multi_account_comment_categories')
    op.drop_index(op.f('ix_instagram_user_sentiment_overview_id'), table_name='instagram_user_sentiment_overview')
    op.drop_table('instagram_user_sentiment_overview')
    op.drop_index(op.f('ix_instagram_user_insights_id'), table_name='instagram_user_insights')
    op.drop_table('instagram_user_insights')
    op.drop_index(op.f('ix_instagram_posts_info_id'), table_name='instagram_posts_info')
    op.drop_table('instagram_posts_info')
    op.drop_index(op.f('ix_instagram_lda_topics_id'), table_name='instagram_lda_topics')
    op.drop_table('instagram_lda_topics')
    op.drop_index(op.f('ix_instagram_comment_categories_id'), table_name='instagram_comment_categories')
    op.drop_table('instagram_comment_categories')
    op.drop_index(op.f('ix_business_ideas_id'), table_name='business_ideas')
    op.drop_table('business_ideas')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_instagram_user_info_id'), table_name='instagram_user_info')
    op.drop_table('instagram_user_info')
    # ### end Alembic commands ###
