"""create business model model

Revision ID: 8501cab94b4a
Revises: 0b3eea949ded
Create Date: 2025-04-12 14:22:44.374690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8501cab94b4a'
down_revision: Union[str, None] = '0b3eea949ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=True),
    sa.Column('problem_definition', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('competitors', sa.Text(), nullable=True),
    sa.Column('customer_persona', sa.Text(), nullable=True),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('competitive_advantage', sa.Text(), nullable=True),
    sa.Column('key_metrics', sa.Text(), nullable=True),
    sa.Column('key_resources', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('minio_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_models_business_id'), 'business_models', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_models_id'), 'business_models', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_models_id'), table_name='business_models')
    op.drop_index(op.f('ix_business_models_business_id'), table_name='business_models')
    op.drop_table('business_models')
    # ### end Alembic commands ###
