"""init tables

Revision ID: 8dc73e156fcf
Revises: 
Create Date: 2025-04-22 20:28:44.306550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dc73e156fcf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_user_info',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('follows_count', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('business_category', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=2083), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('total_posts', sa.Integer(), nullable=False),
    sa.Column('igtv_videos', sa.Integer(), nullable=True),
    sa.Column('highlight_reels', sa.Integer(), nullable=True),
    sa.Column('address_city_name', sa.String(length=255), nullable=True),
    sa.Column('address_lat', sa.Float(), nullable=True),
    sa.Column('address_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_instagram_user_info_id'), 'instagram_user_info', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('business_ideas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_proposal', sa.Text(), nullable=True),
    sa.Column('products_services', sa.Text(), nullable=True),
    sa.Column('ideal_customer', sa.Text(), nullable=True),
    sa.Column('problem_solved', sa.Text(), nullable=True),
    sa.Column('differentiators', sa.Text(), nullable=True),
    sa.Column('challenges_opportunities', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_ideas_id'), 'business_ideas', ['id'], unique=False)
    op.create_index(op.f('ix_business_ideas_user_id'), 'business_ideas', ['user_id'], unique=False)
    op.create_table('instagram_comment_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category_type', sa.String(length=100), nullable=False),
    sa.Column('category_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_comment_categories_id'), 'instagram_comment_categories', ['id'], unique=False)
    op.create_table('instagram_lda_topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('topic_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_lda_topics_id'), 'instagram_lda_topics', ['id'], unique=False)
    op.create_table('instagram_posts_info',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_post', sa.String(), nullable=False),
    sa.Column('instagram_user_id', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mentions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('is_sponsored', sa.Boolean(), nullable=True),
    sa.Column('post_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type_post', sa.String(length=50), nullable=True),
    sa.Column('url_post', sa.String(length=2083), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instagram_user_id'], ['instagram_user_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_post')
    )
    op.create_index(op.f('ix_instagram_posts_info_id'), 'instagram_posts_info', ['id'], unique=False)
    op.create_table('instagram_user_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('final_insight', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_user_insights_id'), 'instagram_user_insights', ['id'], unique=False)
    op.create_table('instagram_user_sentiment_overview',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('positive_comments', sa.Integer(), nullable=False),
    sa.Column('negative_comments', sa.Integer(), nullable=False),
    sa.Column('neutral_comments', sa.Integer(), nullable=False),
    sa.Column('positive_ratio', sa.Float(), nullable=False),
    sa.Column('negative_ratio', sa.Float(), nullable=False),
    sa.Column('neutral_ratio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_user_sentiment_overview_id'), 'instagram_user_sentiment_overview', ['id'], unique=False)
    op.create_table('multi_account_comment_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category_type', sa.String(length=100), nullable=False),
    sa.Column('category_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_account_comment_categories_id'), 'multi_account_comment_categories', ['id'], unique=False)
    op.create_table('multi_account_lda_topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('topic_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_account_lda_topics_id'), 'multi_account_lda_topics', ['id'], unique=False)
    op.create_table('multi_account_sentiment_overview',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('positive_comments', sa.Integer(), nullable=False),
    sa.Column('negative_comments', sa.Integer(), nullable=False),
    sa.Column('neutral_comments', sa.Integer(), nullable=False),
    sa.Column('positive_ratio', sa.Float(), nullable=False),
    sa.Column('negative_ratio', sa.Float(), nullable=False),
    sa.Column('neutral_ratio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_account_sentiment_overview_id'), 'multi_account_sentiment_overview', ['id'], unique=False)
    op.create_table('business_canvas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_idea_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('bucket_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_idea_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_canvas_id'), 'business_canvas', ['id'], unique=False)
    op.create_table('business_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=True),
    sa.Column('problem_definition', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('competitors', sa.Text(), nullable=True),
    sa.Column('customer_persona', sa.Text(), nullable=True),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('competitive_advantage', sa.Text(), nullable=True),
    sa.Column('key_metrics', sa.Text(), nullable=True),
    sa.Column('key_resources', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('minio_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_models_business_id'), 'business_models', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_models_id'), 'business_models', ['id'], unique=False)
    op.create_table('business_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('brief_status', sa.String(), nullable=True),
    sa.Column('business_canvas_status', sa.String(), nullable=True),
    sa.Column('competitive_analysis_status', sa.String(), nullable=True),
    sa.Column('brief_session_id', sa.String(), nullable=True),
    sa.Column('business_canvas_id', sa.String(), nullable=True),
    sa.Column('competitive_analysis_id', sa.String(), nullable=True),
    sa.Column('brief_completed_at', sa.DateTime(), nullable=True),
    sa.Column('business_canvas_completed_at', sa.DateTime(), nullable=True),
    sa.Column('competitive_analysis_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_progress_business_id'), 'business_progress', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_progress_id'), 'business_progress', ['id'], unique=False)
    op.create_table('business_understanding',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_idea_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_research_path', sa.String(), nullable=True),
    sa.Column('state_of_art_path', sa.String(), nullable=True),
    sa.Column('market_research_status', sa.String(), nullable=True),
    sa.Column('state_of_art_status', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_idea_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_understanding_id'), 'business_understanding', ['id'], unique=False)
    op.create_table('business_validations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'ERROR', name='validationstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('data_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_validations_id'), 'business_validations', ['id'], unique=False)
    op.create_table('competitor_research',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'ERROR', name='competitorresearchstatus'), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_research_id'), 'competitor_research', ['id'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_idea_id', sa.String(), nullable=True),
    sa.Column('competitor_name', sa.String(), nullable=False),
    sa.Column('key_feature', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('x_url', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('tiktok_url', sa.String(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_idea_id'], ['business_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_id'), 'competitors', ['id'], unique=False)
    op.create_table('instagram_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('username_commentator', sa.String(length=50), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['instagram_comment_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_comments_id'), 'instagram_comments', ['id'], unique=False)
    op.create_table('instagram_post_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('llm_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_index(op.f('ix_instagram_post_images_id'), 'instagram_post_images', ['id'], unique=False)
    op.create_table('instagram_post_sentiment_summary',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('positive_comments', sa.Integer(), nullable=False),
    sa.Column('negative_comments', sa.Integer(), nullable=False),
    sa.Column('neutral_comments', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_post_sentiment_summary_id'), 'instagram_post_sentiment_summary', ['id'], unique=False)
    op.create_table('multi_account_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['multi_account_comment_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_user_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_account_comments_id'), 'multi_account_comments', ['id'], unique=False)
    op.create_table('instagram_comment_emotions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('emotion_label', sa.String(length=50), nullable=False),
    sa.Column('emotion_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['instagram_comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_comment_emotions_id'), 'instagram_comment_emotions', ['id'], unique=False)
    op.create_table('instagram_comment_sentiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('sentiment_negative', sa.Float(), nullable=False),
    sa.Column('sentiment_neutral', sa.Float(), nullable=False),
    sa.Column('sentiment_positive', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['instagram_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_comment_sentiments_id'), 'instagram_comment_sentiments', ['id'], unique=False)
    op.create_table('instagram_image_colors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('red', sa.Integer(), nullable=False),
    sa.Column('green', sa.Integer(), nullable=False),
    sa.Column('blue', sa.Integer(), nullable=False),
    sa.Column('proportion', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('blue >= 0 AND blue <= 255', name='valid_blue'),
    sa.CheckConstraint('green >= 0 AND green <= 255', name='valid_green'),
    sa.CheckConstraint('proportion >= 0 AND proportion <= 1', name='valid_proportion'),
    sa.CheckConstraint('red >= 0 AND red <= 255', name='valid_red'),
    sa.ForeignKeyConstraint(['image_id'], ['instagram_post_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_image_colors_id'), 'instagram_image_colors', ['id'], unique=False)
    op.create_table('instagram_scraping_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('competitor_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('dataset_id_profile', sa.String(), nullable=True),
    sa.Column('dataset_id_posts', sa.String(), nullable=True),
    sa.Column('dataset_id_comments', sa.String(), nullable=True),
    sa.Column('dataset_id_reels', sa.String(), nullable=True),
    sa.Column('dataset_id_igtv', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('profile_status', sa.String(), nullable=True),
    sa.Column('posts_status', sa.String(), nullable=True),
    sa.Column('comments_status', sa.String(), nullable=True),
    sa.Column('reels_status', sa.String(), nullable=True),
    sa.Column('igtv_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results_limit', sa.Integer(), nullable=True),
    sa.Column('max_comments', sa.Integer(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_scraping_jobs_id'), 'instagram_scraping_jobs', ['id'], unique=False)
    op.create_table('research_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_understanding_id', sa.String(), nullable=True),
    sa.Column('business_idea_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('research_type', sa.String(), nullable=False),
    sa.Column('depth', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.String(), nullable=False),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_understanding_id'], ['business_understanding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_tasks_id'), 'research_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_research_tasks_request_id'), 'research_tasks', ['request_id'], unique=False)
    op.drop_index('ix_pipeline_schedule_global_data_product_uuid', table_name='pipeline_schedule')
    op.drop_index('ix_pipeline_schedule_pipeline_uuid', table_name='pipeline_schedule')
    op.drop_index('ix_pipeline_schedule_token', table_name='pipeline_schedule')
    op.drop_table('pipeline_schedule')
    op.drop_table('role_permission')
    op.drop_index('ix_tag_name', table_name='tag')
    op.drop_table('tag')
    op.drop_index('ix_tag_association_taggable_id', table_name='tag_association')
    op.drop_table('tag_association')
    op.drop_index('ix_role_name', table_name='role')
    op.drop_table('role')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_table('user_project')
    op.drop_table('user_role')
    op.drop_index('ix_pipeline_run_backfill_id', table_name='pipeline_run')
    op.drop_index('ix_pipeline_run_execution_date', table_name='pipeline_run')
    op.drop_index('ix_pipeline_run_pipeline_schedule_id', table_name='pipeline_run')
    op.drop_index('ix_pipeline_run_pipeline_uuid', table_name='pipeline_run')
    op.drop_index('ix_pipeline_run_status', table_name='pipeline_run')
    op.drop_table('pipeline_run')
    op.drop_index('ix_oauth2_access_token_token', table_name='oauth2_access_token')
    op.drop_table('oauth2_access_token')
    op.drop_table('permission')
    op.drop_table('pipeline_schedule_event_matcher_association')
    op.drop_table('event_matcher')
    op.drop_index('ix_oauth2_application_client_id', table_name='oauth2_application')
    op.drop_table('oauth2_application')
    op.drop_index('ix_block_run_pipeline_run_id', table_name='block_run')
    op.drop_table('block_run')
    op.drop_table('backfill')
    op.drop_table('secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('repo_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('key_uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='secret_pkey'),
    sa.UniqueConstraint('name', 'key_uuid', name='name_key_uuid_uc')
    )
    op.create_table('backfill',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('backfill_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('block_uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('end_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('failed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('interval_type', postgresql.INTERVAL(), autoincrement=False, nullable=True),
    sa.Column('interval_units', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pipeline_schedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pipeline_uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('start_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('INITIAL', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='status'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pipeline_schedule_id'], ['pipeline_schedule.id'], name='backfill_pipeline_schedule_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='backfill_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('block_run',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('pipeline_run_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('block_uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('INITIAL', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'UPSTREAM_FAILED', 'CONDITION_FAILED', name='blockrunstatus'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], name='block_run_pipeline_run_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='block_run_pkey')
    )
    op.create_index('ix_block_run_pipeline_run_id', 'block_run', ['pipeline_run_id'], unique=False)
    op.create_table('oauth2_application',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('oauth2_application_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('authorization_grant_type', postgresql.ENUM('AUTHORIZATION_CODE', 'CLIENT_CREDENTIALS', name='authorizationgranttype'), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('client_type', postgresql.ENUM('PRIVATE', 'PUBLIC', name='clienttype'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('redirect_uris', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='oauth2_application_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='oauth2_application_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_oauth2_application_client_id', 'oauth2_application', ['client_id'], unique=True)
    op.create_table('event_matcher',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('event_matcher_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('event_type', postgresql.ENUM('AWS_EVENT', name='eventtype'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pattern', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='event_matcher_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pipeline_schedule_event_matcher_association',
    sa.Column('pipeline_schedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_matcher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_matcher_id'], ['event_matcher.id'], name='pipeline_schedule_event_matcher_associati_event_matcher_id_fkey'),
    sa.ForeignKeyConstraint(['pipeline_schedule_id'], ['pipeline_schedule.id'], name='pipeline_schedule_event_matcher_assoc_pipeline_schedule_id_fkey')
    )
    op.create_table('permission',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('permission_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('entity', postgresql.ENUM('GLOBAL', 'PROJECT', 'PIPELINE', name='entity'), autoincrement=False, nullable=True),
    sa.Column('access', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entity_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='permission_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='permission_user_id'),
    sa.PrimaryKeyConstraint('id', name='permission_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('oauth2_access_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('oauth2_application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['oauth2_application_id'], ['oauth2_application.id'], name='oauth2_access_token_oauth2_application_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='oauth2_access_token_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='oauth2_access_token_pkey')
    )
    op.create_index('ix_oauth2_access_token_token', 'oauth2_access_token', ['token'], unique=True)
    op.create_table('pipeline_run',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('pipeline_schedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pipeline_uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('execution_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('INITIAL', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='pipelinerunstatus'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('passed_sla', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('event_variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('backfill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('executor_type', postgresql.ENUM('AZURE_CONTAINER_INSTANCE', 'ECS', 'GCP_CLOUD_RUN', 'K8S', 'LOCAL_PYTHON', 'LOCAL_PYTHON_FORCE', 'PYSPARK', name='executortype'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['backfill_id'], ['backfill.id'], name='pipeline_run_backfill_id'),
    sa.ForeignKeyConstraint(['pipeline_schedule_id'], ['pipeline_schedule.id'], name='pipeline_run_pipeline_schedule_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pipeline_run_pkey')
    )
    op.create_index('ix_pipeline_run_status', 'pipeline_run', ['status'], unique=False)
    op.create_index('ix_pipeline_run_pipeline_uuid', 'pipeline_run', ['pipeline_uuid'], unique=False)
    op.create_index('ix_pipeline_run_pipeline_schedule_id', 'pipeline_run', ['pipeline_schedule_id'], unique=False)
    op.create_index('ix_pipeline_run_execution_date', 'pipeline_run', ['execution_date'], unique=False)
    op.create_index('ix_pipeline_run_backfill_id', 'pipeline_run', ['backfill_id'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='user_role_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_role_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_role_pkey')
    )
    op.create_table('user_project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('root_project_uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('project_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_project_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_project_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('owner', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password_salt', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('roles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('role_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='role_user_id'),
    sa.PrimaryKeyConstraint('id', name='role_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_role_name', 'role', ['name'], unique=True)
    op.create_table('tag_association',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('taggable_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('taggable_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='tag_association_tag_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tag_association_pkey'),
    sa.UniqueConstraint('tag_id', 'taggable_id', 'taggable_type', name='tag_id_taggable_id_taggable_type_uc')
    )
    op.create_index('ix_tag_association_taggable_id', 'tag_association', ['taggable_id', 'taggable_type'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tag_pkey')
    )
    op.create_index('ix_tag_name', 'tag', ['name'], unique=True)
    op.create_table('role_permission',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name='role_permission_permission_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='role_permission_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='role_permission_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='role_permission_pkey')
    )
    op.create_table('pipeline_schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pipeline_uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('schedule_type', postgresql.ENUM('TIME', 'API', 'EVENT', name='scheduletype'), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('schedule_interval', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='schedulestatus'), autoincrement=False, nullable=True),
    sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sla', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('repo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('global_data_product_uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_enabled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pipeline_schedule_pkey')
    )
    op.create_index('ix_pipeline_schedule_token', 'pipeline_schedule', ['token'], unique=False)
    op.create_index('ix_pipeline_schedule_pipeline_uuid', 'pipeline_schedule', ['pipeline_uuid'], unique=False)
    op.create_index('ix_pipeline_schedule_global_data_product_uuid', 'pipeline_schedule', ['global_data_product_uuid'], unique=False)
    op.drop_index(op.f('ix_research_tasks_request_id'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_id'), table_name='research_tasks')
    op.drop_table('research_tasks')
    op.drop_index(op.f('ix_instagram_scraping_jobs_id'), table_name='instagram_scraping_jobs')
    op.drop_table('instagram_scraping_jobs')
    op.drop_index(op.f('ix_instagram_image_colors_id'), table_name='instagram_image_colors')
    op.drop_table('instagram_image_colors')
    op.drop_index(op.f('ix_instagram_comment_sentiments_id'), table_name='instagram_comment_sentiments')
    op.drop_table('instagram_comment_sentiments')
    op.drop_index(op.f('ix_instagram_comment_emotions_id'), table_name='instagram_comment_emotions')
    op.drop_table('instagram_comment_emotions')
    op.drop_index(op.f('ix_multi_account_comments_id'), table_name='multi_account_comments')
    op.drop_table('multi_account_comments')
    op.drop_index(op.f('ix_instagram_post_sentiment_summary_id'), table_name='instagram_post_sentiment_summary')
    op.drop_table('instagram_post_sentiment_summary')
    op.drop_index(op.f('ix_instagram_post_images_id'), table_name='instagram_post_images')
    op.drop_table('instagram_post_images')
    op.drop_index(op.f('ix_instagram_comments_id'), table_name='instagram_comments')
    op.drop_table('instagram_comments')
    op.drop_index(op.f('ix_competitors_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_competitor_research_id'), table_name='competitor_research')
    op.drop_table('competitor_research')
    op.drop_index(op.f('ix_business_validations_id'), table_name='business_validations')
    op.drop_table('business_validations')
    op.drop_index(op.f('ix_business_understanding_id'), table_name='business_understanding')
    op.drop_table('business_understanding')
    op.drop_index(op.f('ix_business_progress_id'), table_name='business_progress')
    op.drop_index(op.f('ix_business_progress_business_id'), table_name='business_progress')
    op.drop_table('business_progress')
    op.drop_index(op.f('ix_business_models_id'), table_name='business_models')
    op.drop_index(op.f('ix_business_models_business_id'), table_name='business_models')
    op.drop_table('business_models')
    op.drop_index(op.f('ix_business_canvas_id'), table_name='business_canvas')
    op.drop_table('business_canvas')
    op.drop_index(op.f('ix_multi_account_sentiment_overview_id'), table_name='multi_account_sentiment_overview')
    op.drop_table('multi_account_sentiment_overview')
    op.drop_index(op.f('ix_multi_account_lda_topics_id'), table_name='multi_account_lda_topics')
    op.drop_table('multi_account_lda_topics')
    op.drop_index(op.f('ix_multi_account_comment_categories_id'), table_name='multi_account_comment_categories')
    op.drop_table('multi_account_comment_categories')
    op.drop_index(op.f('ix_instagram_user_sentiment_overview_id'), table_name='instagram_user_sentiment_overview')
    op.drop_table('instagram_user_sentiment_overview')
    op.drop_index(op.f('ix_instagram_user_insights_id'), table_name='instagram_user_insights')
    op.drop_table('instagram_user_insights')
    op.drop_index(op.f('ix_instagram_posts_info_id'), table_name='instagram_posts_info')
    op.drop_table('instagram_posts_info')
    op.drop_index(op.f('ix_instagram_lda_topics_id'), table_name='instagram_lda_topics')
    op.drop_table('instagram_lda_topics')
    op.drop_index(op.f('ix_instagram_comment_categories_id'), table_name='instagram_comment_categories')
    op.drop_table('instagram_comment_categories')
    op.drop_index(op.f('ix_business_ideas_user_id'), table_name='business_ideas')
    op.drop_index(op.f('ix_business_ideas_id'), table_name='business_ideas')
    op.drop_table('business_ideas')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_instagram_user_info_id'), table_name='instagram_user_info')
    op.drop_table('instagram_user_info')
    # ### end Alembic commands ###
