# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/noit.com.co
cert = /etc/letsencrypt/live/noit.com.co/cert.pem
privkey = /etc/letsencrypt/live/noit.com.co/privkey.pem
chain = /etc/letsencrypt/live/noit.com.co/chain.pem
fullchain = /etc/letsencrypt/live/noit.com.co/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 4cc59bba330701def5082444c91633ff
pref_challs = http-01,
pre_hook = systemctl stop nginx
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
