from apify_client import ApifyClient
import os
from dotenv import load_dotenv

load_dotenv()

# Initialize the ApifyClient with your API token
client = ApifyClient(os.getenv("APIFY_API_KEY"))

# Prepare the Actor input
run_input = {
    "cookie": [
        {
            "domain": ".linkedin.com",
            "expirationDate": 1746143676.122925,
            "hostOnly": False,
            "httpOnly": True,
            "name": "__cf_bm",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "Fko_XMjsDHZhlCOygcBWWHVspHSAawzwMhHB_bJYMTk-1746141876-1.0.1.1-vH7resNg4qIMPFjJXMOtUkvyJjnFsYYePbLuF_UVdlpv5UeBxme_POO5V5nAesrEa2_S8UItODVlDQtwFr.3.AsagOLuJiXsFE0iNYLH9l8",
            "id": 1
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1752884072,
            "hostOnly": False,
            "httpOnly": False,
            "name": "_gcl_au",
            "path": "/",
            "sameSite": "unspecified",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "1.1.1322076727.1745108072.837929275.1745374342.1745374341",
            "id": 2
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1753137901.842247,
            "hostOnly": False,
            "httpOnly": False,
            "name": "_guid",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "8e7ed30b-33f4-4fc1-a920-4244320917ca",
            "id": 3
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1778803833,
            "hostOnly": False,
            "httpOnly": False,
            "name": "_uetvid",
            "path": "/",
            "sameSite": "unspecified",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "a8ceedc01d7b11f089d02d206cd25445",
            "id": 4
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1748733881,
            "hostOnly": False,
            "httpOnly": False,
            "name": "aam_uuid",
            "path": "/",
            "sameSite": "unspecified",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "46656712865117814083326447949730879644",
            "id": 5
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1761693881,
            "hostOnly": False,
            "httpOnly": False,
            "name": "AMCV_14215E3D5995C57C0A495C55%40AdobeOrg",
            "path": "/",
            "sameSite": "unspecified",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "-637568504%7CMCIDTS%7C20210%7CMCMID%7C46434623685229746993379606228785949527%7CMCAAMLH-1746746681%7C4%7CMCAAMB-1746746681%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1746149081s%7CNONE%7CvVersion%7C5.1.1%7CMCCIDH%7C1882960244",
            "id": 6
        },
        {
            "domain": ".linkedin.com",
            "hostOnly": False,
            "httpOnly": False,
            "name": "AMCVS_14215E3D5995C57C0A495C55%40AdobeOrg",
            "path": "/",
            "sameSite": "unspecified",
            "secure": False,
            "session": True,
            "storeId": "0",
            "value": "1",
            "id": 7
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1748733878.80258,
            "hostOnly": False,
            "httpOnly": False,
            "name": "AnalyticsSyncHistory",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "AQLX7tBtVuNvbgAAAZaOKpqxYfRD5_vxH24v5-8Q9hOis773dPZ9bwEseG9aftTRcTvTFeaySBMXaQHaLN_DBg",
            "id": 8
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1777677879.116791,
            "hostOnly": False,
            "httpOnly": False,
            "name": "bcookie",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "\"v=2&e9826e31-f6e6-40d7-8b8e-f0f6563e8508\"",
            "id": 9
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1776644067.376807,
            "hostOnly": False,
            "httpOnly": True,
            "name": "dfpfpt",
            "path": "/",
            "sameSite": "unspecified",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "f71e055f8f504181950a1dbe07ded357",
            "id": 10
        },
        {
            "domain": ".linkedin.com",
            "hostOnly": False,
            "httpOnly": True,
            "name": "fptctx2",
            "path": "/",
            "sameSite": "unspecified",
            "secure": True,
            "session": True,
            "storeId": "0",
            "value": "taBcrIH61PuCVH7eNCyH0LNKRXFdWqLJ6b8ywJyet7WDZCYhOQHajRyvV8xYspLj6WFyqpNcu9QUYisEpTSTouvaV64BfiF5ZQzO0n5A8q6ly%252fsoySTID8ldBbN8%252frum9TxqADgHOV%252fgRj9%252fIxH01GnVmLFniEMBDE2bRGm4DwQNL87NmAFhxPUfE4fJj2PlqOpRwCoJGwY0NQloY3goK04ivcUdfsoInVDqya6A2DbF2zZZBvFVSGn0hmKh4u%252bElQFLy7qIYE%252b%252fOFH1aQroDNp%252fieAwBtrvnQI4ESMW8TNuzRXlhuFlZkDDGIynEPiAK2M6qw7TJS68bsxGNTYMhhYv32pWG8he6qyL4N0U1nA%253d",
            "id": 11
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1760659961,
            "hostOnly": False,
            "httpOnly": False,
            "name": "gpv_pn",
            "path": "/",
            "sameSite": "unspecified",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "developer.linkedin.com%2Fproduct-catalog",
            "id": 12
        },
        {
            "domain": ".linkedin.com",
            "hostOnly": False,
            "httpOnly": False,
            "name": "lang",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": True,
            "storeId": "0",
            "value": "v=2&lang=en-us",
            "id": 13
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1753917879.116552,
            "hostOnly": False,
            "httpOnly": False,
            "name": "li_sugr",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "fd24a079-ef6f-4581-93bb-8e0d84f403da",
            "id": 14
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1777677876.122697,
            "hostOnly": False,
            "httpOnly": False,
            "name": "liap",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "true",
            "id": 15
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1746193414.585518,
            "hostOnly": False,
            "httpOnly": False,
            "name": "lidc",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "\"b=TB86:s=T:r=T:a=T:p=T:g=5280:u=830:x=1:i=1746141879:t=1746193414:v=2:sig=AQHrjbnbDWaQIMfvO0vFchIZhYyHHpF5\"",
            "id": 16
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1748733879.005442,
            "hostOnly": False,
            "httpOnly": False,
            "name": "lms_ads",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "AQEskMRwVTeOTAAAAZaOKptwq9ZSmWt0BtEJ_UD7NHt8l_5X9imvb71-OdN7PqMQl44edpOrTAmNEtUfoUnD6i0SQE476Vjg",
            "id": 17
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1748733879.005528,
            "hostOnly": False,
            "httpOnly": False,
            "name": "lms_analytics",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "AQEskMRwVTeOTAAAAZaOKptwq9ZSmWt0BtEJ_UD7NHt8l_5X9imvb71-OdN7PqMQl44edpOrTAmNEtUfoUnD6i0SQE476Vjg",
            "id": 18
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1760659834,
            "hostOnly": False,
            "httpOnly": False,
            "name": "mbox",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "session#1615756b70f04f08abf7633ed65e0467#1745109694|PC#1615756b70f04f08abf7633ed65e0467.34_0#1760659834",
            "id": 19
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1760659832,
            "hostOnly": False,
            "httpOnly": False,
            "name": "s_ips",
            "path": "/",
            "sameSite": "unspecified",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "1190",
            "id": 20
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1760659832,
            "hostOnly": False,
            "httpOnly": False,
            "name": "s_tp",
            "path": "/",
            "sameSite": "unspecified",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "5750",
            "id": 21
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1760659961,
            "hostOnly": False,
            "httpOnly": False,
            "name": "s_tslv",
            "path": "/",
            "sameSite": "unspecified",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "1745107961449",
            "id": 22
        },
        {
            "domain": ".linkedin.com",
            "expirationDate": 1748733878.802411,
            "hostOnly": False,
            "httpOnly": False,
            "name": "UserMatchHistory",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "AQKg9IeJzjzp4QAAAZaOKpqxsV7iwhxdzUPaSIOhy8LBigc2oySc3FVK2ZY6GbQpyUeNx8GRSsn0VoDyDI-duhZkU0kDb0D1c6YhJoYOfvDqU6dJrT_c7WjESYDURhvuj0vtkQnCy_ZqAvI1ubf8vEUACtYM4tHZ1hqlQvuE3KS3EgrVaTcZCBrdNHCxRMLMe1UY8k6ACStPTYW6LHBv989o5Soyb99IajaSyuWiiYbldU46NMGPF-WGkm7LOJTi-KmrTPcK0D78s5xMOAJJTlnLSoK41_NN7QgI4UYLCSd4sVxychLO3VVy7EhD3XsP-XG2Op9WmRoJrofaX5tZXHyzhCY4VJnUilvzS1sAw3IWQTyUsw",
            "id": 23
        },
        {
            "domain": ".www.linkedin.com",
            "expirationDate": 1777677879.005611,
            "hostOnly": False,
            "httpOnly": True,
            "name": "bscookie",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "\"v=1&20250213142546640e3432-6ecd-421c-8570-75d9a579872eAQEEr0DkNN2AIMErNImZHQnC4Q31sMZ2\"",
            "id": 24
        },
        {
            "domain": ".www.linkedin.com",
            "expirationDate": 1777677876.122738,
            "hostOnly": False,
            "httpOnly": False,
            "name": "JSESSIONID",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "\"ajax:4802930318244996953\"",
            "id": 25
        },
        {
            "domain": ".www.linkedin.com",
            "expirationDate": 1777677876.122627,
            "hostOnly": False,
            "httpOnly": True,
            "name": "li_at",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "AQEDAS25u-oDk4ExAAABllCM8eMAAAGWsjcTLE0AB4K8QrFlnTTQ_ftu3TfNvu78r_F7SeuxnBg795gjzXS6cLR8fwKZv0tRML1m_O119SwrerFoIMlvNv1wOxl8FQXi7KWMFrqlCUucDdltQSr9kHQB",
            "id": 26
        },
        {
            "domain": ".www.linkedin.com",
            "expirationDate": 1776644136.700978,
            "hostOnly": False,
            "httpOnly": True,
            "name": "li_rm",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "AQG7KLMXkk31vwAAAZZQi0DhYYBNV22c3_Ir3FUSGH4XYPMshUPxBuvi2OTTt2-XIkcbhvzOZESY89rp-hGagLIoFKOVs7v5CARamuMkr2uBlY3X6G4044XI",
            "id": 27
        },
        {
            "domain": ".www.linkedin.com",
            "expirationDate": 1761693876,
            "hostOnly": False,
            "httpOnly": False,
            "name": "li_theme",
            "path": "/",
            "sameSite": "unspecified",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "light",
            "id": 28
        },
        {
            "domain": ".www.linkedin.com",
            "expirationDate": 1761693876,
            "hostOnly": False,
            "httpOnly": False,
            "name": "li_theme_set",
            "path": "/",
            "sameSite": "unspecified",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "app",
            "id": 29
        },
        {
            "domain": ".www.linkedin.com",
            "expirationDate": 1747351476,
            "hostOnly": False,
            "httpOnly": False,
            "name": "timezone",
            "path": "/",
            "sameSite": "unspecified",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "America/Bogota",
            "id": 30
        },
        {
            "domain": "www.linkedin.com",
            "expirationDate": 1760660135,
            "hostOnly": True,
            "httpOnly": False,
            "name": "g_state",
            "path": "/",
            "sameSite": "unspecified",
            "secure": False,
            "session": False,
            "storeId": "0",
            "value": "{\"i_l\":0}",
            "id": 31
        }
    ],
    "deepScrape": True,
    "limitPerSource": 10,
    "maxDelay": 8,
    "minDelay": 2,
    "proxy": {
        "useApifyProxy": True,
        "apifyProxyCountry": "US"
    },
    "rawData": False,
    "urls": [
        "https://www.linkedin.com/company/nvidia/"
    ]
}

# Run the Actor and wait for it to finish
run = client.actor("kfiWbq3boy3dWKbiL").call(run_input=run_input)

# Fetch and print Actor results from the run's dataset (if there are any)
for item in client.dataset(run["defaultDatasetId"]).iterate_items():
    print(item)