import os
import json
from openai import OpenAI
from app.services.storage.minio_service import MinioService

class InstagramInsightAnalyzer:
    def __init__(self, username, output_folder, api_key):
        self.username = username
        self.output_folder = output_folder
        self.api_key = api_key
        self.client = OpenAI(api_key=api_key)
        self.minio_service = MinioService(bucket_name=settings.MINIO_BUCKET_NAME)

    async def load_json_from_minio(self, object_path):
        """Loads a JSON file from MinIO and returns its content as a Python dictionary."""
        try:
            json_data = await self.minio_service.get_object_data(object_path)
            return json.loads(json_data)
        except Exception as e:
            print(f"❌ Error loading JSON from MinIO ({object_path}): {e}")
            return None

    def generate_expert_prompt(self, image_analysis_text, scraped_posts_text):
        """Generates an expert-level prompt combining image analysis with Instagram post data."""
        return [
            {
                "role": "system",
                "content": "Eres un experto en marketing digital, branding y engagement en redes sociales. Tu tarea es analizar la coherencia entre las imágenes publicadas y los textos de los posts, y sugerir mejoras estratégicas para optimizar la conversión y el engagement."
            },
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": "Analiza la coherencia entre la imagen y el texto del post."},
                    {"type": "text", "text": f"### **📸 Análisis de Imágenes:**\n{image_analysis_text}"},
                    {"type": "text", "text": f"### **📝 Datos de Posts Scrapeados:**\n{scraped_posts_text}"},
                    {"type": "text", "text": "🔍 Evalúa el CTA, los colores y el engagement general."}
                ]
            }
        ]

    async def get_insights_from_openai(self, image_analysis_text, scraped_posts_text):
        """Sends combined data to OpenAI and retrieves insights generated by the LLM."""
        try:
            response = self.client.chat.completions.create(
                model="gpt-4o",
                messages=self.generate_expert_prompt(image_analysis_text, scraped_posts_text),
                temperature=0.7,
                max_tokens=1500
            )
            return response.choices[0].message.content
        except Exception as e:
            print(f"❌ Error analyzing with OpenAI: {e}")
            return None

    async def process_instagram_analysis(self):
        """Processes Instagram image and post analysis, generates insights, and saves results."""
        try:
            image_analysis_path = f"{self.output_folder}/{self.username}/image_analysis_report.json"
            posts_filtered_path = f"{self.output_folder}/{self.username}/instagram_posts.json"

            image_analysis = await self.load_json_from_minio(image_analysis_path)
            scraped_posts = await self.load_json_from_minio(posts_filtered_path)

            if not image_analysis or not scraped_posts:
                print("❌ Missing required data for analysis.")
                return None

            image_analysis_text = json.dumps(image_analysis, indent=4, ensure_ascii=False)
            scraped_posts_text = json.dumps(scraped_posts, indent=4, ensure_ascii=False)

            final_insights = await self.get_insights_from_openai(image_analysis_text, scraped_posts_text)

            if final_insights:
                output_path = f"{self.output_folder}/{self.username}/global_insights.json"
                await self.minio_service.upload_content(
                    object_name=output_path,
                    data=json.dumps({"final_insight": final_insights}, indent=4, ensure_ascii=False),
                    content_type="application/json"
                )
                print(f"✅ Insights saved to MinIO: {output_path}")
                return output_path
            else:
                print("❌ Failed to generate insights.")
                return None
        except Exception as e:
            print(f"❌ Error processing Instagram analysis: {e}")
            return None