import os
import requests
import zipfile
from apify_client import ApifyClient
from dotenv import load_dotenv
from app.services.storage.minio_service import MinioService
import aiohttp


load_dotenv()

class InstagramImageScraper:

    def __init__(self, username, post_limit, image_limit, output_folder):
        self.api_key = os.getenv("APIFY_API_KEY")
        self.username = username
        self.minio_service = MinioService(bucket_name="lattice-businesses")
        self.post_limit = post_limit
        self.image_limit = image_limit
        self.output_folder = output_folder

    def get_images_zip_url(self):
        """
        Executes the Instagram Scraper on Apify and retrieves the ZIP file URL containing images.

        :param api_key: Your Apify API Key.
        :param username: The Instagram profile username.
        :param post_limit: Maximum number of posts to scrape.
        :return: A string with the URL of the ZIP file containing images.
        """
        try:
            # Create an ApifyClient instance using the provided API key
            client = ApifyClient(self.api_key)

            # Configuration settings for the Instagram Scraper
            instagram_scraper_input = {
                "directUrls": [f"https://www.instagram.com/{self.username}/"],
                "resultsType": "posts",
                "resultsLimit": self.post_limit,
                "proxy": {
                    "useApifyProxy": True,
                    "apifyProxyGroups": ["RESIDENTIAL"]
                },
            }

            # Run the Instagram Scraper actor
            print("\U0001f680 Running Instagram Scraper...")
            run = client.actor("apify/instagram-scraper").call(run_input=instagram_scraper_input)

            # Extract the dataset ID from the response
            dataset_id = run.get("defaultDatasetId", None)
            if not dataset_id:
                raise ValueError("Dataset ID not found.")

            print(f"📁 Dataset generated by Instagram Scraper: {dataset_id}")

            # Configuration for the Image Downloader actor
            run_input = {
                "datasetId": dataset_id,
                "pathToImageUrls": "displayUrl",
                "limit": self.post_limit,
                "fileNameFunction": "({url, md5}) => md5(url)",
                "proxyConfiguration": {"useApifyProxy": True},
            }

            # Run the Image Downloader actor
            print("\U0001f680 Running image downloader actor...")
            run = client.actor("MLHNPjUxSBA2uGvZw").call(run_input=run_input)

            # Extract the ZIP file URL from the resulting dataset
            zip_file_url = None
            dataset_id_images = run.get("defaultDatasetId", None)
            for item in client.dataset(dataset_id_images).iterate_items():
                zip_file_url = item.get("zipFileUrl", None)
                if zip_file_url:
                    break

            if not zip_file_url:
                raise ValueError("ZIP file URL not found.")

            print(f"🔗 ZIP file URL generated: {zip_file_url}")
            return zip_file_url

        except Exception as e:
            print(f"❌ Error during image scraping: {e}")
            return None

    async def scrape_instagram_posts(self):
        """
        Executes the Instagram Scraper to extract posts and saves the data as JSON in the specified folder.
        """
        try:
            # Create an ApifyClient instance using the provided API key
            client = ApifyClient(self.api_key)

            # Configuration settings for the Instagram Scraper
            instagram_scraper_input = {
                "directUrls": [f"https://www.instagram.com/{self.username}/"],
                "resultsType": "posts",
                "resultsLimit": self.post_limit,
                "proxy": {
                    "useApifyProxy": True,
                    "apifyProxyGroups": ["RESIDENTIAL"]
                },
            }

            # Run the Instagram Scraper actor to get posts
            print("\U0001f680 Running Instagram Scraper for posts...")
            run = client.actor("apify/instagram-scraper").call(run_input=instagram_scraper_input)

            # Extract the dataset ID for the posts
            dataset_id = run.get("defaultDatasetId", None)
            if not dataset_id:
                raise ValueError("Dataset ID for posts not found.")

            print(f"📁 Dataset generated for posts: {dataset_id}")

            # Build the API endpoint to retrieve the data as JSON
            dataset_url = f"https://api.apify.com/v2/datasets/{dataset_id}/items?format=json"
            async with aiohttp.ClientSession() as session:
                async with session.get(dataset_url) as response:
                    if response.status == 200:
                        data = await response.text()
                        
                        await self.minio_service.upload_content(
                            object_name=self.output_folder + "/img_posts.json",
                            data=data,
                            content_type="application/json",
                            metadata={
                                "username": self.username,
                                "post_limit": self.post_limit
                            }
                        )
                    else:
                        raise ValueError(f"Error al descargar JSON. Código: {response.status}")

        except Exception as e:
            print(f"❌ Error during post scraping: {e}")

    async def upload_images_to_minio_and_cleanup(self, temporal_zip_folder: str) -> list:
        """
        Uploads images from the local folder to MinIO and then deletes them from local storage.
        
        Args:
            output_folder: Path to the folder containing the extracted images
            minio_service: Instance of MinioService for uploading to MinIO
            
        Returns:
            list: List of successfully uploaded image paths in MinIO
        """
        uploaded_files = []
        try:
            # Walk through the output folder
            for root, _, files in os.walk(temporal_zip_folder):
                for file in files:
                    if file.lower().endswith((".png", ".jpg", ".jpeg")):
                        # Construct full local path
                        local_file_path = os.path.join(root, file)
                        file_img_name = os.path.basename(local_file_path)
                        # Determine content type based on file extension
                        content_type = "image/jpeg" if file.lower().endswith(("jpg", "jpeg")) else "image/png"
                        
                        try:
                            # Create object name (path in MinIO)
                            object_name = self.output_folder+f"/images/{file_img_name}"
                            
                            # Upload file to MinIO
                            with open(local_file_path, 'rb') as f:
                                file_data = f.read()

                                await self.minio_service.upload_content(
                                    object_name=object_name,
                                    data=file_data,
                                    content_type=content_type
                                )
                            
                            uploaded_files.append(object_name)
                            print(f"✅ Uploaded: {file} -> {object_name}")
                            
                            # Delete local file after successful upload
                            os.remove(local_file_path)
                            print(f"🗑️ Deleted local file: {local_file_path}")
                        
                        except Exception as e:
                            print(f"❌ Error processing {file}: {str(e)}")
                            continue
            
            # Delete the ZIP file if it exists
            zip_path = os.path.join(temporal_zip_folder, "images.zip")
            if os.path.exists(zip_path):
                os.remove(zip_path)
                print(f"🗑️ Deleted ZIP file: {zip_path}")
            
            # Optionally remove the empty folder
            if not os.listdir(temporal_zip_folder):
                os.rmdir(temporal_zip_folder)
                print(f"🗑️ Removed empty folder: {temporal_zip_folder}")
            
            print(f"📊 Total files uploaded: {len(uploaded_files)}")
            return uploaded_files
        
        except Exception as e:
            print(f"❌ Error during upload and cleanup process: {str(e)}")
            raise

    async def download_and_extract_images(self, zip_file_url, output_folder):
        """
        Downloads the ZIP file containing images from Apify and extracts them to the specified local folder.

        :param zip_file_url: URL of the ZIP file generated by Apify.
        :param output_folder: Path to the local folder where the images will be saved.
        """
        try:
            # Ensure the folder exists (create if it does not)
            if not os.path.exists(output_folder):
                os.makedirs(output_folder)
                print(f"📂 Folder created at: {output_folder}")
            else:
                print(f"📂 Folder already exists at: {output_folder}")

            # Define the path for the ZIP file
            zip_path = os.path.join(output_folder, "images.zip")

            # Download the ZIP file
            print(f"🔗 Downloading ZIP file from: {zip_file_url}")
            response = requests.get(zip_file_url)
            if response.status_code == 200:
                with open(zip_path, 'wb') as f:
                    f.write(response.content)
                print(f"✅ ZIP file saved at: {zip_path}")
            else:
                raise ValueError(f"Failed to download ZIP file. Status code: {response.status_code}")

            # Extract the ZIP file
            print("📦 Extracting images...")
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(output_folder)
            print(f"🖼️ Images extracted to: {output_folder}")

            # Upload to MinIO and cleanup
            uploaded_files = await self.upload_images_to_minio_and_cleanup(output_folder)
            return uploaded_files


        except Exception as e:
            print(f"❌ Error during image extraction: {e}")

    async def lattice_scrap(self):
        """
        Main function that executes Instagram scraping, saves posts as JSON, and downloads images locally.
        """
        try:

            # Scrape and save posts as JSON
            await self.scrape_instagram_posts()
            # Retrieve and download images
            zip_file_url = self.get_images_zip_url()
            temporal_zip_folder = os.getenv("ZIP_TEMPORAL_FILE_PATH")
            if zip_file_url:
                await self.download_and_extract_images(zip_file_url, temporal_zip_folder)

            await self.upload_images_to_minio_and_cleanup(temporal_zip_folder)
        except Exception as e:
            print(f"❌ Error in the main process: {e}")
